# Service

apiVersion: v1
kind: Service
metadata:
  name: datakudos
  labels:
    app: datakudos
spec:
  type: ClusterIP
  selector:
    app: datakudos
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP